declare const classNames: {
  readonly root: "root";
  readonly header: "header";
  readonly title: "title";
  readonly namespaceFilter: "namespaceFilter";
  readonly scrollBody: "scrollBody";
  readonly loadingMessage: "loadingMessage";
  readonly errorMessage: "errorMessage";
  readonly statuses: "statuses";
  readonly overviewStatusCards: "overviewStatusCards";
  readonly overviewStatusCard: "overviewStatusCard";
  readonly overviewStatusLabel: "overviewStatusLabel";
  readonly overviewStatusValue: "overviewStatusValue";
  readonly healthSummary: "healthSummary";
  readonly summaryTitle: "summaryTitle";
  readonly summaryText: "summaryText";
  readonly emptyState: "emptyState";
  readonly chartsRow: "chartsRow";
  readonly chart: "chart";
  readonly apiNamespaceSelect: "apiNamespaceSelect";
  readonly eventsNote: "eventsNote";
};
export = classNames;
